version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - pnpm-store:/root/.local/share/pnpm/store
    environment:
      - NODE_ENV=development
    command: npm run dev
    network_mode: "host"

volumes:
  pnpm-store:
